BEGIN TRANSACTION;
CREATE TABLE "sua_tabela" (
"Numero_da_Ocorrencia" TEXT,
  "Numero_da_Ficha" TEXT,
  "Operador_Padronizado" TEXT,
  "Classificacao_da_Ocorrência" TEXT,
  "Data_da_Ocorrencia" TEXT,
  "Hora_da_Ocorrência" TEXT,
  "Municipio" TEXT,
  "UF" TEXT,
  "Regiao" TEXT,
  "Descricao_do_Tipo" TEXT,
  "ICAO" TEXT,
  "Latitude" TEXT,
  "Longitude" TEXT,
  "Tipo_de_Aerodromo" TEXT,
  "Historico" TEXT,
  "Matricula" TEXT,
  "Categoria_da_Aeronave" TEXT,
  "Operador" TEXT,
  "Tipo_de_Ocorrencia" TEXT,
  "Fase_da_Operacao" TEXT,
  "Operacao" TEXT,
  "Danos_a_Aeronave" TEXT,
  "Aerodromo_de_Destino" TEXT,
  "Aerodromo_de_Origem" TEXT,
  "Lesoes_Fatais_Tripulantes" TEXT,
  "Lesoes_Fatais_Passageiros" TEXT,
  "Lesoes_Fatais_Terceiros" TEXT,
  "Lesoes_Graves_Tripulantes" TEXT,
  "Lesoes_Graves_Passageiros" TEXT,
  "Lesoes_Graves_Terceiros" TEXT,
  "Lesoes_Leves_Tripulantes" TEXT,
  "Lesoes_Leves_Passageiros" TEXT,
  "Lesoes_Leves_Terceiros" TEXT,
  "Ilesos_Tripulantes" TEXT,
  "Ilesos_Passageiros" TEXT,
  "Lesoes_Desconhecidas_Tripulantes" TEXT,
  "Lesoes_Desconhecidas_Passageiros" TEXT,
  "Lesoes_Desconhecidas_Terceiros" TEXT,
  "Modelo" TEXT,
  "CLS" TEXT,
  "Tipo_ICAO" TEXT,
  "PMD" TEXT,
  "Numero_de_Assentos" TEXT,
  "Nome_do_Fabricante" TEXT,
  "PSSO" TEXT
);
INSERT INTO "sua_tabela" VALUES('39780','202308329845','AZUL','Incidente','2023-10-11','19:55:00','MARINGÁ','PR','Sul','COLISÃO COM AVE','SBMG','-23,2846','-52,0044','Público','A aeronave decolou do aeroporto Afonso Pena (SBCT), Curitiba, PR, com destino ao aeroporto Silvio Name Junior (SBMG), Maringá, PR, a fim de realizar transporte aéreo público regular. Durante a fase de pouso, houve colisão com ave.','PRAQK','TPR','AZUL LINHAS AEREAS BRASILEIRAS S.A','BIRD','Pouso','Voo Regular','Nenhum','SBMG ','SBCT ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'ATR-72-212A (600)','L2T','AT76','22000','76','ATR - GIE AVIONS DE TRANSPORT RÉGIONAL','verdadeiro');
INSERT INTO "sua_tabela" VALUES('30446','2021477242','JOSE PORFIRIO DE BRITO JUNIOR','Acidente','2021-11-26','00:27','UBATUBA','SP','Sudeste','FALHA OU MAU FUNCIONAMENTO DO MOTOR','Fora de Aeródromo','-23,4133','-44,7997','-','A aeronave decolou do aeródromo Estadual de Campos dos Amarais - Prefeito Francisco Amaral (SDAM), município de Campinas, SP, com destino ao Aeródromo de Jacarepaguá - Roberto Marinho (SBJR), Rio de Janeiro, RJ, a fim de realizar transporte de passageiro, com dois tripulantes e um passageiro a bordo. Durante voo de cruzeiro, a aeronave teve uma emergência e realizou uma amerissagem.','PPWRS','TPP','JOSE PORFIRIO DE BRITO JUNIOR','SCF-PP','Cruzeiro','Voo Privado','Destruída','SBJR','SDAM','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1','1',NULL,'PA-34-220T','L2P','PA34','2155','7','PIPER AIRCRAFT','verdadeiro');
INSERT INTO "sua_tabela" VALUES('30991','2022874362','SANA AGRO AÉREA SOCIEDADE SIMPLES','Acidente','2022-01-24','10:30','CORUMBATAÍ','SP','Sudeste','FALHA OU MAU FUNCIONAMENTO DO MOTOR','APUA','-22,2386','-47,7064','APUA','A aeronave decolou da APUA Pista Serra (ZZZZ), Corumbatai, SP, para um voo local de aplicação de defensivo agricola com um piloto a bordo. Após a decolagem, a aeronave realizou pouso de emergência em área de cultivo.','PTUUH','S05','SANA AGRO AÉREA SOCIEDADE SIMPLES','SCF-PP','Decolagem','Operação Agrícola','Substancial',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,'EMB-202A','L1P','IPAN','1800','1','NEIVA','verdadeiro');
INSERT INTO "sua_tabela" VALUES('30444','2021010931','PASSAREDO TRANSPORTES AEREOS S.A','Ocorrência Anormal','2021-11-12','14:15','BRASÍLIA','DF','Centro-Oeste','FALHA OU MAU FUNCIONAMENTO DE SISTEMA / COMPONENTE','SBBR','-1,38472','-48,4789','Público','A AERONAVE DECOLOU DO AERÓDROMO LEITE LOPES (SBRP), RIBEIRÃO PRETO, SP, COM DESTINO AO AERÓDROMO PRESIDENTE JUSCELINO KUBITSCHEK (SBBR), BRASÍLIA, DF, A FIM DE REALIZAR TRANSPORTE AÉREO PÚBLICO REGULAR, COM QUATRO TRIPULANTES E QUARENTA E NOVE PASSAGEIROS A BORDO. DURANTE A FASE DE ESTACIONAMENTO, COM O MOTOR ACIONADO EM HOTEL MODE (HÉLICE TRAVADA), OCORREU UM ALARME DE FOGO NO MOTOR 2. APÓS A AÇÃO DA EQUIPE DE MANUTENÇÃO, FOI CONSTATADO SER UM ALARME FALSO.','PRPDO','TPR','PASSAREDO TRANSPORTES AEREOS S.A','SCF-NP','Estacionamento','Voo Regular','Nenhum',NULL,'SBBR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'4','49',NULL,NULL,NULL,'ATR-72-212A','L2T','AT75','23000','75','ATR - GIE AVIONS DE TRANSPORT RÉGIONAL','verdadeiro');
INSERT INTO "sua_tabela" VALUES('30991','2022874362','SANA AGRO AÉREA SOCIEDADE SIMPLES','Acidente','2022-01-24','10:30','CORUMBATAÍ','SP','Sudeste','COLISÃO COM OBSTÁCULO DURANTE A DECOLAGEM E POUSO','APUA','-22,2386','-47,7064','APUA','A aeronave decolou da APUA Pista Serra (ZZZZ), Corumbatai, SP, para um voo local de aplicação de defensivo agricola com um piloto a bordo. Após a decolagem, a aeronave realizou pouso de emergência em área de cultivo.','PTUUH','S05','SANA AGRO AÉREA SOCIEDADE SIMPLES','CTOL','Decolagem','Operação Agrícola','Substancial',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,'EMB-202A','L1P','IPAN','1800','1','NEIVA','verdadeiro');
INSERT INTO "sua_tabela" VALUES('31286','2022290567','CHC DO BRASIL TÁXI AÉREO S.A.','Ocorrência Anormal','2022-02-04','07:30','RIO DE JANEIRO','RJ','Sudeste','FALHA OU MAU FUNCIONAMENTO DE SISTEMA / COMPONENTE','SBJR','-22,9875','-43,37','Público','A aeronave decolou da Plataforma Petrobrás FPSO P-69, com destino ao Aeródromo de Jacarepaguá (SBJR), Rio de Janeiro, RJ, para a realização de um voo de translado de passageiros. Durante a inspeção pós-voo foi identificado que a maçaneta externa (trinco) da porta principal estava faltando.A aeronave não teve danos.','PRBGU','TPX','CHC DO BRASIL TÁXI AÉREO S.A.','SCF-NP','Indeterminada','Táxi Aéreo','Nenhum','SBJR','SBJR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'S-92A','H2T','S92','12020','21','SIKORSKY AIRCRAFT','verdadeiro');
INSERT INTO "sua_tabela" VALUES('31326','2022689649','TAM','Incidente','2022-01-14','06:03','CURITIBA','PR','Sul','COLISÃO COM AVE','SBCT','-25,5317','-49,1761','Público','A aeronave iniciou decolagem do Aeroporto Afonso Pena (SBCT), Curitiba, PR, com destino ao Aeroporto Presidente Juscelino Kubitschek (SBBR), Brasília, DF, a fim de realizar transporte aéreo público regular. Durante a corrida de decolagem, ocorreu colisão com pássaros. A decolagem foi abortada.','PTXPM','TPR','TAM LINHAS AEREAS S.A','BIRD','Decolagem','Voo Regular','Leve','SBBR','SBCT',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'7','190',NULL,NULL,NULL,'A321-211','L2J','A321','89000','231','AIRBUS S.A.S.','verdadeiro');
INSERT INTO "sua_tabela" VALUES('31427','2022344899','LIDER TAXI AEREO�S A AIR BRASIL','Incidente','2022-02-23','14:00','MOSSORÓ','RN','Nordeste','OUTROS','SBMS','-4,93111','-36,3386','Público','A aeronave decolou do Aeródromo Dix-Sept Rosado (SBMS), Mossoró, RN, por volta das 13h40min (UTC), com destino a Unidade Marítima Ubarana2 (PUB2), Mossoró, RN, a fim realizar voo de transporte, com dois pilotos e quatro passageiros a bordo. Após o pouso, o comandante percebeu que havia pousado na Unidade Marítima Ubarana3 (PUB3). Na sequência, a tripulação decolou, realizando o pouso conforme planejado inicialmente, na Unidade Marítima Ubarana2.','PTGAD','TPX','LIDER TAXI AEREO S.A. - AIR BRASIL','OTHR','Pouso','Táxi Aéreo','Nenhum',NULL,'SBMS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2','4',NULL,NULL,NULL,'EC135 T3','H2T','EC35','2980','7','AHD','verdadeiro');
INSERT INTO "sua_tabela" VALUES('31325','2022049954','COMPANHIA BRASILEIRA DE DESENVOLVIMENTO IMOBILIÁRIO LTDA.','Incidente','2021-12-09','11:53','GUARULHOS','SP','Sudeste','FALHA OU MAU FUNCIONAMENTO DO MOTOR','SBGR','-23,4356','-46,4731','Público','A aeronave decolou do aeródromo de Congonhas (SBSP), em São Paulo, SP, com destino ao aeródromo Afonso Pena (SBCT), em Curitiba, PR, para um voo privado com 02 tripulantes e 02 passageiros a bordo. Após a decolagem, a aeronave apresentou perda de potência no motor direito e realizou procedimento de corte. Em coordenação com o controle de área, alternou o pouso para o aeródromo Governador André Franco Montoro (SBGR), em Guarulhos, SP. O pouso ocorreu sem anormalidades.','PPLFV','TPP','COMPANHIA BRASILEIRA DE DESENVOLVIMENTO IMOBILIÁRIO LTDA.','SCF-PP','Subida','Voo Privado','Nenhum','SBCT','SBSP',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2','2',NULL,NULL,NULL,'31','L2J','LJ31','7031','9','LEARJET','verdadeiro');
INSERT INTO "sua_tabela" VALUES('31428','2022235928','FLORIPA FLIGHT TRAINING','Incidente Grave','2022-02-24','16:27','JAGUARUNA','SC','Sul','FALHA OU MAU FUNCIONAMENTO DO MOTOR','SBJA','-28,6753','-49,0603','Público','A aeronave decolou do Aeródromo de Hercílio Luz (SBFL), no município de Florianópolis, SC, com destino inicial ao Aeródromo Regional Sul (SBJA), no município de Jaguaruna, SC, por volta das 15h27min (UTC), a fim de realizar voo de instrução com dois tripulantes e um passageiro a bordo. Após uma arremetida em SBJA e ao atingir 400ft em subida, a aeronave perdeu potência e pousou em frente, vindo a sair da pista pela extremidade. A aeronave não teve danos. Os tripulantes e o passageiro saíram ilesos.','PRMGX','PRI','FLORIPA FLIGHT TRAIN.ESC.AV,CIVIL LT-EPP','SCF-PP','Arremetida','Voo de Instrução','Nenhum','SBJA','SBFL',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2','1',NULL,NULL,NULL,'172M','L1P','C172','1043','4','CESSNA AIRCRAFT','verdadeiro');
INSERT INTO "sua_tabela" VALUES('31428','2022235928','FLORIPA FLIGHT TRAINING','Incidente Grave','2022-02-24','16:27','JAGUARUNA','SC','Sul','EXCURSÃO DE PISTA','SBJA','-28,6753','-49,0603','Público','A aeronave decolou do Aeródromo de Hercílio Luz (SBFL), no município de Florianópolis, SC, com destino inicial ao Aeródromo Regional Sul (SBJA), no município de Jaguaruna, SC, por volta das 15h27min (UTC), a fim de realizar voo de instrução com dois tripulantes e um passageiro a bordo. Após uma arremetida em SBJA e ao atingir 400ft em subida, a aeronave perdeu potência e pousou em frente, vindo a sair da pista pela extremidade. A aeronave não teve danos. Os tripulantes e o passageiro saíram ilesos.','PRMGX','PRI','FLORIPA FLIGHT TRAIN.ESC.AV,CIVIL LT-EPP','RE','Arremetida','Voo de Instrução','Nenhum','SBJA','SBFL',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2','1',NULL,NULL,NULL,'172M','L1P','C172','1043','4','CESSNA AIRCRAFT','verdadeiro');
INSERT INTO "sua_tabela" VALUES('34406','2022484911','AERO CLUB DE BRAGANÇA PAULISTA','Incidente','2022-10-12','14:15:00','BRAGANÇA PAULISTA','SP','Sudeste','FALHA OU MAU FUNCIONAMENTO DE SISTEMA / COMPONENTE','SBBP','-22,5845','-46,3215','Público','Aeronave decolou do aeródromo Estadual Arthur Siqueira (SBBP), Bragança Paulista, SP, para um voo local de instrução. Durante um dos treinamentos de toque e arremetida, houve o estouro do pneu do trem de pouso principal direito, abortando-se a arremetida. A aeronave parou sobre a pista.','PRJBD','PRI','AERO CLUB DE BRAGANÇA PAULISTA','SCF-NP','Corrida após pouso','Voo Privado','Leve','SBBP','SBBP',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2',NULL,NULL,NULL,NULL,'152','L1P','C152','757','2','CESSNA AIRCRAFT','verdadeiro');
INSERT INTO "sua_tabela" VALUES('34407','2022130140','JOSUÉ MÁRIO DA SILVA','Incidente Grave','2022-10-11','18:10:00','GOIÂNIA','GO','Centro-Oeste','EXCURSÃO DE PISTA','SBNV','-16,3733','-49,2053','Público','A Aeronave decolou do Aeródromo Nacional de Aviação (SBNV), Goiânia, GO, por volta das 17h10min (UTC), a fim de realizar voo local no setor oeste para apresentação a um possível comprador da aeronave, com 01 tripulante a bordo e 02 passageiros. Após 1h de voo, ao realizar o pouso final na pista 14, já na corrida de solo, a aeronave perdeu a reta, vindo a sair da pista pela sua lateral esquerda.','PTENZ','TPP','JOSUÉ MÁRIO DA SILVA','RE','Corrida após pouso','Voo Privado','Leve','SBNV','SBNV',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1','2',NULL,NULL,NULL,'EMB-810C','L2P','PA34','2073','7','EMBRAER','verdadeiro');
INSERT INTO "sua_tabela" VALUES('33446','2022809448','PESSOA EMPREENDIMENTOS EIRELI','Incidente Grave','2022-07-19','13:26','NOVA CANTU','PR','Sul','FALHA OU MAU FUNCIONAMENTO DO MOTOR','Fora de Aeródromo','-24,5669','-52,5786','-','A aeronave decolou do aeródromo Mocellin II (SIZM), Dois Vizinhos, PR, com destino ao aeródromo Silvio Name Junior (SBMG), Maringá, PR, aproximadamente, às 12h15min (UTC), a fim de realizar voo privado, com um piloto a bordo. Durante voo de cruzeiro, aproximadamente às 13h26min (UTC), o piloto alegou ter entrado fumaça e óleo na cabine, de forma que declarou emergência e pousou em uma Área de pouso para uso Aeroagrícola, localizada na região de Nova Cantú, PR, por volta das 13h30min (UTC).','PUBPH','PET','PESSOA EMPREENDIMENTOS EIRELI','SCF-PP','Cruzeiro','Voo Privado','Leve','SBMG','SIZM',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,'CONQUEST 180','L1P','ULAC','000750','002','INPAER IND.LTDA','falso');
INSERT INTO "sua_tabela" VALUES('33446','2022809448','PESSOA EMPREENDIMENTOS EIRELI','Incidente Grave','2022-07-19','13:26','NOVA CANTU','PR','Sul','FOGO/FUMAÇA','Fora de Aeródromo','-24,5669','-52,5786','-','A aeronave decolou do aeródromo Mocellin II (SIZM), Dois Vizinhos, PR, com destino ao aeródromo Silvio Name Junior (SBMG), Maringá, PR, aproximadamente, às 12h15min (UTC), a fim de realizar voo privado, com um piloto a bordo. Durante voo de cruzeiro, aproximadamente às 13h26min (UTC), o piloto alegou ter entrado fumaça e óleo na cabine, de forma que declarou emergência e pousou em uma Área de pouso para uso Aeroagrícola, localizada na região de Nova Cantú, PR, por volta das 13h30min (UTC).','PUBPH','PET','PESSOA EMPREENDIMENTOS EIRELI','F-NI','Cruzeiro','Voo Privado','Leve','SBMG','SIZM',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,'CONQUEST 180','L1P','ULAC','000750','002','INPAER IND.LTDA','falso');
INSERT INTO "sua_tabela" VALUES('33446','2022809448','PESSOA EMPREENDIMENTOS EIRELI','Incidente Grave','2022-07-19','13:26','NOVA CANTU','PR','Sul','OUTROS','Fora de Aeródromo','-24,5669','-52,5786','-','A aeronave decolou do aeródromo Mocellin II (SIZM), Dois Vizinhos, PR, com destino ao aeródromo Silvio Name Junior (SBMG), Maringá, PR, aproximadamente, às 12h15min (UTC), a fim de realizar voo privado, com um piloto a bordo. Durante voo de cruzeiro, aproximadamente às 13h26min (UTC), o piloto alegou ter entrado fumaça e óleo na cabine, de forma que declarou emergência e pousou em uma Área de pouso para uso Aeroagrícola, localizada na região de Nova Cantú, PR, por volta das 13h30min (UTC).','PUBPH','PET','PESSOA EMPREENDIMENTOS EIRELI','OTHR','Cruzeiro','Voo Privado','Leve','SBMG','SIZM',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,'CONQUEST 180','L1P','ULAC','000750','002','INPAER IND.LTDA','falso');
INSERT INTO "sua_tabela" VALUES('33670','2022775726','SUBSECRETARIA ADJ. DE OPERACOES AEREAS','Incidente','2022-04-03','13:25','ARARUAMA','RJ','Sudeste','COLISÃO COM AVE','Fora de Aeródromo','-22,575','-42,1239','-','A aeronave decolou do Aeroporto de Jacarepaguá-Roberto Marinho (SBJR), Rio de Janeiro, RJ, com destino ao Aeroporto Bartolomeu Lisandro (SBCP), Campos dos Goytacazes, RJ, a fim de realizar voo privado, com dois tripulantes e quatro passageiros a bordo.Durante o voo ocorreu a colisão da aeronave com um pássaro. O voo retornou para o aeródromo de origem.','PRGRJ','ADE','SUBSECRETARIA ADJ. DE OPERACOES AEREAS','BIRD','Cruzeiro','Voo Privado','Leve','SBCP','SBJR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2','4',NULL,NULL,NULL,'AW109SP','H2T','A109','3175','8','AGUSTA','verdadeiro');
INSERT INTO "sua_tabela" VALUES('33675','2022993965','AZUL','Incidente','2022-03-27','12:10','RECIFE','PE','Nordeste','FALHA OU MAU FUNCIONAMENTO DE SISTEMA / COMPONENTE','SBRF','-8,12639','-34,9228','Público','A aeronave decolou do Aeroporto dos Guararapes - Gilberto Freyre (SBRF), Recife, PE, com destino ao Aeroporto Zumbi dos Palmares (SBMO), Maceió, AL, com 04 (quatro) tripulantes e 69 (sessenta e nove) passageiros a bordo, a fim de realizar transporte aéreo público regular. Durante a fase de subida, a aeronave apresentou falha no sistema de refrigeração da cabine. Após a realização dos procedimentos previstos em manual, o voo retornou ao aeródromo de origem.','PRAKF','TPR','AZUL LINHAS AEREAS BRASILEIRAS S.A','SCF-NP','Subida','Voo Regular','Nenhum','SBMO','SBRF',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'4','69',NULL,NULL,NULL,'ATR-72-212A','L2T','AT76','23000','75','ATR - GIE AVIONS DE TRANSPORT RÉGIONAL','verdadeiro');
INSERT INTO "sua_tabela" VALUES('33671','2022659709','AZUL LINHAS AÉREAS BRASILEIRAS S.A.','Incidente','2022-03-31','08:31','FLORIANÓPOLIS','SC','Sul','FALHA OU MAU FUNCIONAMENTO DE SISTEMA / COMPONENTE','SBFL','-27,6703','-48,5525','Público','A aeronave decolou do Aeródromo Hercílio Luz (SBFL), Florianópolis, SC, com destino ao Aeródromo de Viracopos (SBKP), Campinas, SP, com 05 (cinco) tripulantes e 108 (cento e oito) passageiros a bordo, a fim de realizar transporte aéreo público regular. Durante a fase de subida, a aeronave apresentou a mensagem “LG LEVER DISAG” no painel. Após a execução de procedimentos previstos em manual, a tripulação decidiu retornar ao Aeródromo de origem, onde pousou sem maiores anormalidades.','PRAUH','TPR','AZUL LINHAS AÉREAS BRASILEIRAS S.A.','SCF-NP','Subida','Voo Regular','Nenhum','SBKP','SBFL',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'5','108',NULL,NULL,NULL,'ERJ 190-200 LR','L2J','E195','50790','126','EMBRAER','verdadeiro');
INSERT INTO "sua_tabela" VALUES('34407','2022130140','JOSUÉ MÁRIO DA SILVA','Incidente Grave','2022-10-11','18:10:00','GOIÂNIA','GO','Centro-Oeste','PERDA DE CONTROLE NO SOLO','SBNV','-16,3733','-49,2053','Público','A Aeronave decolou do Aeródromo Nacional de Aviação (SBNV), Goiânia, GO, por volta das 17h10min (UTC), a fim de realizar voo local no setor oeste para apresentação a um possível comprador da aeronave, com 01 tripulante a bordo e 02 passageiros. Após 1h de voo, ao realizar o pouso final na pista 14, já na corrida de solo, a aeronave perdeu a reta, vindo a sair da pista pela sua lateral esquerda.','PTENZ','TPP','JOSUÉ MÁRIO DA SILVA','LOC-G','Corrida após pouso','Voo Privado','Leve','SBNV','SBNV',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1','2',NULL,NULL,NULL,'EMB-810C','L2P','PA34','2073','7','EMBRAER','verdadeiro');
INSERT INTO "sua_tabela" VALUES('34407','2022130140','JOSUÉ MÁRIO DA SILVA','Incidente Grave','2022-10-11','18:10:00','GOIÂNIA','GO','Centro-Oeste','FALHA OU MAU FUNCIONAMENTO DE SISTEMA / COMPONENTE','SBNV','-16,3733','-49,2053','Público','A Aeronave decolou do Aeródromo Nacional de Aviação (SBNV), Goiânia, GO, por volta das 17h10min (UTC), a fim de realizar voo local no setor oeste para apresentação a um possível comprador da aeronave, com 01 tripulante a bordo e 02 passageiros. Após 1h de voo, ao realizar o pouso final na pista 14, já na corrida de solo, a aeronave perdeu a reta, vindo a sair da pista pela sua lateral esquerda.','PTENZ','TPP','JOSUÉ MÁRIO DA SILVA','SCF-NP','Corrida após pouso','Voo Privado','Leve','SBNV','SBNV',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1','2',NULL,NULL,NULL,'EMB-810C','L2P','PA34','2073','7','EMBRAER','verdadeiro');
INSERT INTO "sua_tabela" VALUES('34408','2022928412','ASSOCIACAO DE PROPRIETARIOS DE AERONAVES DO ESTADO DO RIO DE JANEIRO - APAERJ','Incidente','2022-10-09','19:12:00','RIO DE JANEIRO','RJ','Sudeste','FALHA OU MAU FUNCIONAMENTO DE SISTEMA / COMPONENTE','SBJR','-22,5916','-43,2215','Público','A aeronave decolou do Aeródromo de Trimonte, Casimiro de Abreu, RJ (SNAO), para o Aeródromo Jacarepaguá - Roberto Marinho, Rio de Janeiro, RJ (SBJR), realizando voo de traslado, com 01 tripulante e 10 passageiros a bordo. Durante a corrida de pouso, a aeronave teve o pneu esquerdo do trem de pouso principal furado.','PTSIN','TPP','ASSOCIACAO DE PROPRIETARIOS DE AERONAVES DO ESTADO DO RIO DE JANEIRO - APAERJ','SCF-NP','Corrida após pouso','Voo Privado','Nenhum','SBJR','SNAO',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1','10',NULL,NULL,NULL,'208B','L1T','C208','3969','10','CESSNA AIRCRAFT','verdadeiro');
INSERT INTO "sua_tabela" VALUES('39632','202327643668','GOL LINHAS AÉREAS S.A.','Incidente','2023-09-26','16:55:00','PORTO ALEGRE','RS','Sul','COLISÃO COM AVE','SBPA','-29,5941','-51,1016','Público','A aeronave decolou do aeroporto Salgado Filho (SBPA), Porto Alegre, RS, com destino ao aeroporto de Guarulhos - Governador André Franco Montoro (SBGR), São Paulo, SP, a fim de realizar transporte aéreo público regular. Durante a fase de decolagem, houve colisão de ave com a parte dianteira da fuselagem.','PRGGZ','TPR','GOL LINHAS AÉREAS S.A.','BIRD','Decolagem','Voo Regular','Nenhum','SBGR','SBPA ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'737-8EH','L2J','B738','70533','196','BOEING COMPANY','verdadeiro');
INSERT INTO "sua_tabela" VALUES('32630','2022532824','AZUL','Incidente','2022-07-05','06:23','CONFINS','MG','Sudeste','FALHA OU MAU FUNCIONAMENTO DE SISTEMA / COMPONENTE','SBCF','-23,0069','-47,1344','Público','A aeronave decolou do aeródromo Marechal Rondon (SBCY), Cuiabá, MT, com destino ao aeródromo de Confins (SBCF), Confins, MG, com 05 (cinco) tripulantes e 83 (oitenta e três) passageiros a bordo, a fim de realizar transporte aéreo público regular. Durante a corrida após o pouso, a aeronave apresentou a mensagem de falha no freio do trem de pouso. Não houve maiores intercorrências.','PRAUP','TPR','AZUL LINHAS AEREAS BRASILEIRAS S.A','SCF-NP','Corrida após pouso','Voo Regular','Leve','SBCF','SBCY',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'5','83',NULL,NULL,NULL,'ERJ 190-200 LR','L2J','E195','50790','126','EMBRAER','verdadeiro');
INSERT INTO "sua_tabela" VALUES('33766','2022765354','INSTITUTO BRASILEIRO DO MEIO AMBIENTE E DOS RECURSOS NATURAIS RENOVÁVEIS ¿ IBAMA','Incidente','2022-08-25','15:55:00','SÃO FÉLIX DO XINGU','PA','Norte','COLISÃO COM OBSTÁCULO DURANTE A DECOLAGEM E POUSO','SNFX','-6,64139','-51,9522','Público','A aeronave decolou do Aeródromo de São Félix do Xingu (SNFX), São Félix do Xingu, PA, por volta das 12h30min (UTC), a fim de efetuar voo local de fiscalização de desmatamento, com três tripulantes e três passageiros a bordo. Durante a missão, foram realizados pousos em clareiras e, após o pouso final em SNFX, foram constatados danos nas pás do rotor principal.','PRHCT','AIF','INSTITUTO BRASILEIRO DO MEIO AMBIENTE E DOS RECURSOS NATURAIS RENOVÁVEIS ¿ IBAMA','CTOL','Pouso','Operação Policial','Leve','SNFX','SNFX',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'3','3',NULL,NULL,NULL,'AS 350 B2','H1T','AS50','2250','6','HELIBRAS','verdadeiro');
INSERT INTO "sua_tabela" VALUES('34126','2022084134','GOL','Incidente','2022-09-15','15:12:00','CONFINS','MG','Sudeste','FALHA OU MAU FUNCIONAMENTO DO MOTOR','SBCF',NULL,NULL,'Público','A aeronave decolou do aeródromo Governador André Franco Montoro (SBGR), Guarulhos, SP, com destino ao aeródromo Deputado Luis Eduardo Magalhães (SBSV), Salvador, BA, com 06(seis) tripulantes e 174 (cento e setenta e quatro) passageiros a bordo, a fim de realizar transporte aéreo público regular. Durante a fase de voo de cruzeiro, a aeronave apresentou falha no motor #1. Após a execução de procedimentos previstos em manual, a tripulação decidiu alternar o voo para o aeródromo Tancredo Neves (SBCF), Confins, MG, onde pousou sem maiores intercorrências.','PSGPF','TPR','GOL LINHAS AEREAS S.A','SCF-PP','Cruzeiro','Voo Regular','Nenhum','SBSV','SBGR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'6','174',NULL,NULL,NULL,'737-8 MAX','L2J','B38M','82190','196','BOEING COMPANY','verdadeiro');
INSERT INTO "sua_tabela" VALUES('34127','2022898872','LUNELLI COMÉRCIO DO VESTUÁRIO LTDA','Incidente','2022-09-17','16:45:00','SOCORRO','SP','Sudeste','PERDA DE CONTROLE NO SOLO',NULL,NULL,NULL,NULL,'A Aeronave decolou do Aeródromo Campo Fontanelle (SBYS), Pirassununga, SP, com destino ao Aeródromo de Socorro (SD4V), Socorro, SP, com um tripulante a bordo, para voo privado. Após o pouso, ao realizar o backtrack sobre a pista, houve o toque da ponta de asa direita da aeronave com o solo.','PTLDO','TPP','LUNELLI COMÉRCIO DO VESTUÁRIO LTDA','LOC-G','Pouso','Voo Privado','Leve',NULL,'SBYS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,'AT-6D','L1P','T6','2404','2','NORTH AMERICAN','verdadeiro');
INSERT INTO "sua_tabela" VALUES('34348','2022718456','FERNANDO HORTA DA CUNHA JUNIOR','Incidente','2022-10-07','16:44:00','UBERABA','MG','Sudeste','FALHA OU MAU FUNCIONAMENTO DE SISTEMA / COMPONENTE','SBUR',NULL,NULL,'Público','A aeronave decolou do Aeroporto Tenente Coronel César Bombonato (SBUL), Uberlândia, MG, com destino ao Aeroporto Mário Almeida Franco (SBUR), Uberaba, MG, a fim de realizar voo de traslado, com um tripulante e 05 passageiros a bordo. Durante a corrida de pouso, a bequilha recolheu inadvertidamente. A aeronave parou dentro dos limites da pista.','PTOEZ','TPP','FERNANDO HORTA DA CUNHA JUNIOR','SCF-NP','Corrida após pouso','Voo Privado','Leve','SBUR','SBUL',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1','5',NULL,NULL,NULL,'210N','L1P','C210','1724','6','CESSNA AIRCRAFT','verdadeiro');
INSERT INTO "sua_tabela" VALUES('34350','2022625446','GOL','Incidente','2022-02-02','16:45:00','GOIÂNIA','GO','Centro-Oeste','CONTATO ANORMAL COM A PISTA','SBGO',NULL,NULL,'Público','A aeronave decolou do aeródromo Santa Genoveva (SBGO), Goiânia, GO, com destino ao aeródromo Deputado Luis Eduardo Magalhães (SBSV), Salvador, BA, com 06 (seis) tripulantes e 144 (cento e quarenta e quatro) passageiros a bordo, a fim de realizar transporte aéreo público regular. Durante a decolagem, a aeronave tocou a cauda na pista. A aeronave pousou no aeródromo de destino, onde se confirmou danos leves limitados ao tailskid.','PRGGL','TPR','GOL LINHAS AEREAS S.A','ARC','Decolagem','Voo Regular','Leve','SBSV','SBGO',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'5','144',NULL,NULL,NULL,'737-8EH','L2J','B738','72500','196','BOEING COMPANY','verdadeiro');
INSERT INTO "sua_tabela" VALUES('34571','2022108235','AZUL','Incidente','2022-10-13','22:26:00','CAMPINAS','SP','Sudeste','FALHA OU MAU FUNCIONAMENTO DE SISTEMA / COMPONENTE','SBKP','-23,0025','-47,0804','Público','A aeronave decolou do aeródromo de Viracopos (SBKP), Campinas, SP, com destino ao aeródromo Lauro Carneiro de Loyola (SBJV), Joinville, SC, com 04(quatro) tripulantes e 59 (cinquenta e nove) passageiros a bordo, a fim de realizar transporte aéreo público regular. Durante a fase de subida, a aeronave apresentou mensagem de falha do TCAS. Após a execução de procedimentos previstos em manual, a aeronave retornou ao aeródromo de origem, onde realizou o pouso sem maiores intercorrências.','PRAKI','TPR','AZUL LINHAS AEREAS BRASILEIRAS S.A','SCF-NP','Subida','Voo Regular','Nenhum','SBJV','SBKP',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'4','59',NULL,NULL,NULL,'ATR-72-212A','L2T','AT76','23000','76','AEROSPATIALE AND ALENIA','verdadeiro');
INSERT INTO "sua_tabela" VALUES('34827','2022829304','MARTINEZ RIDAO AVIACION SL','Incidente','2022-11-05','14:07:00','GUANAMBI','BA','Nordeste','FALHA OU MAU FUNCIONAMENTO DO MOTOR','SNGI','-14,1229','-42,4446','Público','A aeronave decolou do Aeródromo Guararapes – Gilberto Freyre (SBRF), Recife, PE, as 10h00min (UTC), com destino ao Aeródromo Silvio Pettirossi (SGAS), Luque, Paraguai, a fim de realizar voo de traslado, com um piloto a bordo. Em rota, a aeronave apresentou vazamento de óleo do motor e o piloto optou por um pouso de emergência, sendo autorizado pelo órgão de controle a realizá-lo no Aeródromo Isaac Moura Rocha (SNGI), Guanambi, BA. O referido pouso foi realizado com segurança.','ECJIC','Estrangeira','MARTINEZ RIDAO AVIACION SL','SCF-PP','Cruzeiro','Voo Privado','Nenhum','SGAS','SBRF',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'falso');
INSERT INTO "sua_tabela" VALUES('35706','2022445310','MASTER AVIAÇÃO AGRÍCOLA LTDA','Acidente','2022-12-08','20:30:00','NÃO IDENTIFICADA ','MT','Centro-Oeste','INDETERMINADO',NULL,NULL,NULL,NULL,'A aeronave decolou da pista da Fazenda Castanhal (ZZZZ), no município de Rondolândia, MT, com destino a pista da Fazenda Recria (ZZZZ), no município de Colniza, MT, com um piloto a bordo. O voo tinha duração prevista de 40 minutos. O pouso no local de destino não ocorreu. A aeronave permanece desaparecida e as buscas foram declaradas encerradas pelo SALVAERO AMAZÔNICO no dia 18DEZ2022.','PTIJP','S11','MASTER AVIAÇÃO AGRÍCOLA LTDA','UNK','Cruzeiro',NULL,NULL,'**NI','**NI',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,'A188B','L1P','C188','1814','1','CESSNA AIRCRAFT','verdadeiro');
INSERT INTO "sua_tabela" VALUES('36147','2023498375',NULL,'Acidente','2023-01-25','12:00:00','PAULÍNIA','SP','Sudeste','PERDA DE CONTROLE EM VOO','Fora de Aeródromo','-22,4711','-47,0929','-','O paramotor decolou da cidade de Paulínia, SP, para voo local, com um condutor a bordo. Durante o voo, ocorreu a perda de controle e queda do equipamento. A operação era regida pelo RBAC 103.','*****','Sem matrícula',NULL,'LOC-I','Manobra',NULL,'Substancial','***','***','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'verdadeiro');
INSERT INTO "sua_tabela" VALUES('36148','2023941227','GRABMAX EQUIPAMENTOS INDUSTRIAIS LTDA','Acidente','2023-01-25','20:50:00','LAGES','SC','Sul','FALHA OU MAU FUNCIONAMENTO DO MOTOR','Fora de Aeródromo','-27,4735','-50,1611','-','A aeronave decolou do aeródromo Lages (SBLJ), no município de Lages, SC, por volta das 20h40min (UTC), para realizar voo local, com um piloto e um passageiro à bordo. Durante o circuito de tráfego o piloto perdeu altura e a aeronave colidiu contra o solo.','PRCOL','TPP','GRABMAX EQUIPAMENTOS INDUSTRIAIS LTDA','SCF-PP','Circuto de Tráfego','Voo Privado','Substancial','SBLJ ','SBLJ ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1','1',NULL,NULL,NULL,'SR22','L1P','SR22','1542','4','CIRRUS DESIGN','verdadeiro');
INSERT INTO "sua_tabela" VALUES('36306','2023466783','AGROPASTORIL SAO PEDRO LTDA','Incidente Grave','2023-02-08','14:32:00','VITÓRIA','ES','Sudeste','AERÓDROMO','SBVT','-20,1529','-40,1711','Público','A aeronave decolou do Aeródromo Campo de Marte (SBMT), São Paulo, SP, com destino ao Aeródromo Eurico de Aguiar Salles (SBVT), Vitória, ES, por volta das 12h00min (UTC), a fim de realizar um voo de translado. Após a aproximação para o aeródromo de destino, o piloto realizou o pouso da aeronave na pista 06, a qual se encontrava interditada.','PTVLF','TPP','AGROPASTORIL SAO PEDRO LTDA','ADRM','Pouso','Voo Privado','Nenhum','SBVT','SBMT ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,'EMB-810D','L2P','PA34','2155','6','EMBRAER','verdadeiro');
INSERT INTO "sua_tabela" VALUES('36346','2023211240','GLOBAL ADMINISTRAÇÃO E SOLUÇÕES INTEGRADAS LTDA','Acidente','2023-02-09','21:30:00','VARGEM ALTA','ES','Sudeste','COLISÃO COM OBSTÁCULO DURANTE A DECOLAGEM E POUSO','Fora de Aeródromo','-20,385','-40,5839','-','A aeronave decolou do heliponto de N&F (SINF), Serra, ES, com destino ao Aeródromo de Cachoeiro do Itapemirim (SNKI), Cachoeiro do Itapemirim, ES, por volta das 20h30min (UTC), a fim de realizar um voo privado, com um tripulante e um passageiro à bordo. Durante a aproximação para uma área de pouso eventual (ZZZZ), Vargem Alta, ES, a aeronave colidiu com fio de rede elétrica, vindo a chocar-se contra o solo.','PRPLF','TPP','GLOBAL ADMINISTRAÇÃO E SOLUÇÕES INTEGRADAS LTDA','CTOL','Aproximação','Voo Privado','Substancial','SNKI','SINF','1','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'R44 II','H1P','R44','1134','4','ROBINSON HELICOPTER','verdadeiro');
INSERT INTO "sua_tabela" VALUES('36348','2023242037','PLA & SILVA AVIACAO AGRIC.LTDA','Incidente Grave','2023-02-12','11:09:00','SANTA VITÓRIA DO PALMAR ','RS','Sul','COLISÃO COM AVE','APUA','-33,1642','-53,1812','APUA','A aeronave decolou da Área de Pouso de Uso Aeroagrícola (APUA) Bela Visa, no município de Santa Vitória do Palmar, RS, a fim de realizar aplicação de fungicida em uma lavoura de arroz com um piloto a bordo. Durante a aplicação a aeronave realizou uma ação evasiva para evitar colisão contra um pássaro. Após a ação, o piloto sentiu trepidação na aeronave, em seguida optou por alijar a carga e realizar o pouso em campo não preparado.','PTWQR','S05','PLA & SILVA AVIACAO AGRIC.LTDA','BIRD','Voo a baixa altura','Operação Agrícola','Leve','APUA','APUA',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,'A188B','L1P','C188','1905','1','CESSNA AIRCRAFT','verdadeiro');
INSERT INTO "sua_tabela" VALUES('36349','2023261212','FERNANDO ANTONIO COSTA','Acidente','2023-02-08','21:40:00','ERECHIM ','RS','Sul','FALHA OU MAU FUNCIONAMENTO DO MOTOR','Fora de Aeródromo','-27,3948','-52,1715','-','A aeronave decolou do aeródromo AAGV - Associação Aerodesportiva de Getúlio Vargas (SWGL), no município de Getúlio Vargas, RS, por volta de 21h00min (UTC), com destino ao aeródromo Erechim (SSER), no município de Erechim, RS, a fim de realizar voo privado, com um piloto e três passageiros à bordo. Após realização de toque e arremetida, em SSER, ocorreu a perda de potência do motor e a aeronave colidiu contra um poste de média tensão e, posteriormente, contra o solo.','PRFKJ','TPP','FERNANDO ANTONIO COSTA','SCF-PP','Arremetida','Voo Privado','Substancial','SSER','SWGL',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1','3',NULL,NULL,NULL,'PA-32-301XTC','L1P','PA32','1633','6','PIPER AIRCRAFT','verdadeiro');
INSERT INTO "sua_tabela" VALUES('36486','2023420958','JHONATA DO PRADO DE FARIA','Acidente','2023-02-21','10:30:00','NOVO ARIPUANÃ','AM','Norte','INDETERMINADO','Fora de Aeródromo','-5,312','-59,3235','-','Aeronave decolou de local desconhecido para local desconhecido com finalidade desconhecida tendo à bordo 01 tripulante. A aeronave foi encontrada por terceiros em chamas próximo à pousada SUCUNDURI.','PRZPA','AMD','JHONATA DO PRADO DE FARIA','UNK','Indeterminada','Voo Experimental','Substancial','****','****','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'RV-10','L1P','ZZZZ','1224','4','FLYER INDUSTRIA AERONAUTICA LTDA','falso');
COMMIT;
