# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import kv_pb2 as kv__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kv_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PairServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Insert = channel.unary_unary(
                '/kv.PairService/Insert',
                request_serializer=kv__pb2.InsertRequest.SerializeToString,
                response_deserializer=kv__pb2.InsertReply.FromString,
                _registered_method=True)
        self.Query = channel.unary_unary(
                '/kv.PairService/Query',
                request_serializer=kv__pb2.QueryRequest.SerializeToString,
                response_deserializer=kv__pb2.QueryReply.FromString,
                _registered_method=True)
        self.Activate = channel.unary_unary(
                '/kv.PairService/Activate',
                request_serializer=kv__pb2.ActivateRequest.SerializeToString,
                response_deserializer=kv__pb2.ActivateReply.FromString,
                _registered_method=True)
        self.Terminate = channel.unary_unary(
                '/kv.PairService/Terminate',
                request_serializer=kv__pb2.TerminateRequest.SerializeToString,
                response_deserializer=kv__pb2.TerminateReply.FromString,
                _registered_method=True)


class PairServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Insert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Activate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Terminate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PairServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Insert': grpc.unary_unary_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=kv__pb2.InsertRequest.FromString,
                    response_serializer=kv__pb2.InsertReply.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=kv__pb2.QueryRequest.FromString,
                    response_serializer=kv__pb2.QueryReply.SerializeToString,
            ),
            'Activate': grpc.unary_unary_rpc_method_handler(
                    servicer.Activate,
                    request_deserializer=kv__pb2.ActivateRequest.FromString,
                    response_serializer=kv__pb2.ActivateReply.SerializeToString,
            ),
            'Terminate': grpc.unary_unary_rpc_method_handler(
                    servicer.Terminate,
                    request_deserializer=kv__pb2.TerminateRequest.FromString,
                    response_serializer=kv__pb2.TerminateReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kv.PairService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kv.PairService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PairService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kv.PairService/Insert',
            kv__pb2.InsertRequest.SerializeToString,
            kv__pb2.InsertReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kv.PairService/Query',
            kv__pb2.QueryRequest.SerializeToString,
            kv__pb2.QueryReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Activate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kv.PairService/Activate',
            kv__pb2.ActivateRequest.SerializeToString,
            kv__pb2.ActivateReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Terminate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kv.PairService/Terminate',
            kv__pb2.TerminateRequest.SerializeToString,
            kv__pb2.TerminateReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CentralServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/kv.CentralService/Register',
                request_serializer=kv__pb2.RegisterRequest.SerializeToString,
                response_deserializer=kv__pb2.RegisterReply.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/kv.CentralService/Search',
                request_serializer=kv__pb2.SearchRequest.SerializeToString,
                response_deserializer=kv__pb2.SearchReply.FromString,
                _registered_method=True)
        self.Pairing = channel.unary_unary(
                '/kv.CentralService/Pairing',
                request_serializer=kv__pb2.PairingRequest.SerializeToString,
                response_deserializer=kv__pb2.PairingReply.FromString,
                _registered_method=True)
        self.Terminate = channel.unary_unary(
                '/kv.CentralService/Terminate',
                request_serializer=kv__pb2.TerminateRequest.SerializeToString,
                response_deserializer=kv__pb2.TerminateReply.FromString,
                _registered_method=True)


class CentralServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pairing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Terminate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CentralServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=kv__pb2.RegisterRequest.FromString,
                    response_serializer=kv__pb2.RegisterReply.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=kv__pb2.SearchRequest.FromString,
                    response_serializer=kv__pb2.SearchReply.SerializeToString,
            ),
            'Pairing': grpc.unary_unary_rpc_method_handler(
                    servicer.Pairing,
                    request_deserializer=kv__pb2.PairingRequest.FromString,
                    response_serializer=kv__pb2.PairingReply.SerializeToString,
            ),
            'Terminate': grpc.unary_unary_rpc_method_handler(
                    servicer.Terminate,
                    request_deserializer=kv__pb2.TerminateRequest.FromString,
                    response_serializer=kv__pb2.TerminateReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kv.CentralService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kv.CentralService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CentralService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kv.CentralService/Register',
            kv__pb2.RegisterRequest.SerializeToString,
            kv__pb2.RegisterReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kv.CentralService/Search',
            kv__pb2.SearchRequest.SerializeToString,
            kv__pb2.SearchReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pairing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kv.CentralService/Pairing',
            kv__pb2.PairingRequest.SerializeToString,
            kv__pb2.PairingReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Terminate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kv.CentralService/Terminate',
            kv__pb2.TerminateRequest.SerializeToString,
            kv__pb2.TerminateReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
