# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kv.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08kv.proto\x12\x02kv\"+\n\rInsertRequest\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t\"\x1d\n\x0bInsertReply\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\x1b\n\x0cQueryRequest\x12\x0b\n\x03key\x18\x01 \x01(\x05\"\x1b\n\nQueryReply\x12\r\n\x05value\x18\x01 \x01(\t\"\x11\n\x0f\x41\x63tivateRequest\"\x1f\n\rActivateReply\x12\x0e\n\x06result\x18\x01 \x01(\x05\"0\n\x0fRegisterRequest\x12\x0f\n\x07locator\x18\x01 \x01(\t\x12\x0c\n\x04keys\x18\x02 \x03(\x05\"\"\n\rRegisterReply\x12\x11\n\tprocessed\x18\x01 \x01(\x05\",\n\rSearchRequest\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x0e\n\x06\x65xcept\x18\x02 \x01(\t\"\x1e\n\x0bSearchReply\x12\x0f\n\x07locator\x18\x01 \x01(\t\"!\n\x0ePairingRequest\x12\x0f\n\x07locator\x18\x01 \x01(\t\"\x1e\n\x0cPairingReply\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\x12\n\x10TerminateRequest\"\x1f\n\x0eTerminateReply\x12\r\n\x05total\x18\x01 \x01(\x05\x32\xd9\x01\n\x0bPairService\x12.\n\x06Insert\x12\x11.kv.InsertRequest\x1a\x0f.kv.InsertReply\"\x00\x12+\n\x05Query\x12\x10.kv.QueryRequest\x1a\x0e.kv.QueryReply\"\x00\x12\x34\n\x08\x41\x63tivate\x12\x13.kv.ActivateRequest\x1a\x11.kv.ActivateReply\"\x00\x12\x37\n\tTerminate\x12\x14.kv.TerminateRequest\x1a\x12.kv.TerminateReply\"\x00\x32\xe2\x01\n\x0e\x43\x65ntralService\x12\x34\n\x08Register\x12\x13.kv.RegisterRequest\x1a\x11.kv.RegisterReply\"\x00\x12.\n\x06Search\x12\x11.kv.SearchRequest\x1a\x0f.kv.SearchReply\"\x00\x12\x31\n\x07Pairing\x12\x12.kv.PairingRequest\x1a\x10.kv.PairingReply\"\x00\x12\x37\n\tTerminate\x12\x14.kv.TerminateRequest\x1a\x12.kv.TerminateReply\"\x00\x62\x06proto3')



_INSERTREQUEST = DESCRIPTOR.message_types_by_name['InsertRequest']
_INSERTREPLY = DESCRIPTOR.message_types_by_name['InsertReply']
_QUERYREQUEST = DESCRIPTOR.message_types_by_name['QueryRequest']
_QUERYREPLY = DESCRIPTOR.message_types_by_name['QueryReply']
_ACTIVATEREQUEST = DESCRIPTOR.message_types_by_name['ActivateRequest']
_ACTIVATEREPLY = DESCRIPTOR.message_types_by_name['ActivateReply']
_REGISTERREQUEST = DESCRIPTOR.message_types_by_name['RegisterRequest']
_REGISTERREPLY = DESCRIPTOR.message_types_by_name['RegisterReply']
_SEARCHREQUEST = DESCRIPTOR.message_types_by_name['SearchRequest']
_SEARCHREPLY = DESCRIPTOR.message_types_by_name['SearchReply']
_PAIRINGREQUEST = DESCRIPTOR.message_types_by_name['PairingRequest']
_PAIRINGREPLY = DESCRIPTOR.message_types_by_name['PairingReply']
_TERMINATEREQUEST = DESCRIPTOR.message_types_by_name['TerminateRequest']
_TERMINATEREPLY = DESCRIPTOR.message_types_by_name['TerminateReply']
InsertRequest = _reflection.GeneratedProtocolMessageType('InsertRequest', (_message.Message,), {
  'DESCRIPTOR' : _INSERTREQUEST,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.InsertRequest)
  })
_sym_db.RegisterMessage(InsertRequest)

InsertReply = _reflection.GeneratedProtocolMessageType('InsertReply', (_message.Message,), {
  'DESCRIPTOR' : _INSERTREPLY,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.InsertReply)
  })
_sym_db.RegisterMessage(InsertReply)

QueryRequest = _reflection.GeneratedProtocolMessageType('QueryRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUERYREQUEST,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.QueryRequest)
  })
_sym_db.RegisterMessage(QueryRequest)

QueryReply = _reflection.GeneratedProtocolMessageType('QueryReply', (_message.Message,), {
  'DESCRIPTOR' : _QUERYREPLY,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.QueryReply)
  })
_sym_db.RegisterMessage(QueryReply)

ActivateRequest = _reflection.GeneratedProtocolMessageType('ActivateRequest', (_message.Message,), {
  'DESCRIPTOR' : _ACTIVATEREQUEST,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.ActivateRequest)
  })
_sym_db.RegisterMessage(ActivateRequest)

ActivateReply = _reflection.GeneratedProtocolMessageType('ActivateReply', (_message.Message,), {
  'DESCRIPTOR' : _ACTIVATEREPLY,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.ActivateReply)
  })
_sym_db.RegisterMessage(ActivateReply)

RegisterRequest = _reflection.GeneratedProtocolMessageType('RegisterRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERREQUEST,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.RegisterRequest)
  })
_sym_db.RegisterMessage(RegisterRequest)

RegisterReply = _reflection.GeneratedProtocolMessageType('RegisterReply', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERREPLY,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.RegisterReply)
  })
_sym_db.RegisterMessage(RegisterReply)

SearchRequest = _reflection.GeneratedProtocolMessageType('SearchRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHREQUEST,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.SearchRequest)
  })
_sym_db.RegisterMessage(SearchRequest)

SearchReply = _reflection.GeneratedProtocolMessageType('SearchReply', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHREPLY,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.SearchReply)
  })
_sym_db.RegisterMessage(SearchReply)

PairingRequest = _reflection.GeneratedProtocolMessageType('PairingRequest', (_message.Message,), {
  'DESCRIPTOR' : _PAIRINGREQUEST,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.PairingRequest)
  })
_sym_db.RegisterMessage(PairingRequest)

PairingReply = _reflection.GeneratedProtocolMessageType('PairingReply', (_message.Message,), {
  'DESCRIPTOR' : _PAIRINGREPLY,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.PairingReply)
  })
_sym_db.RegisterMessage(PairingReply)

TerminateRequest = _reflection.GeneratedProtocolMessageType('TerminateRequest', (_message.Message,), {
  'DESCRIPTOR' : _TERMINATEREQUEST,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.TerminateRequest)
  })
_sym_db.RegisterMessage(TerminateRequest)

TerminateReply = _reflection.GeneratedProtocolMessageType('TerminateReply', (_message.Message,), {
  'DESCRIPTOR' : _TERMINATEREPLY,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.TerminateReply)
  })
_sym_db.RegisterMessage(TerminateReply)

_PAIRSERVICE = DESCRIPTOR.services_by_name['PairService']
_CENTRALSERVICE = DESCRIPTOR.services_by_name['CentralService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INSERTREQUEST._serialized_start=16
  _INSERTREQUEST._serialized_end=59
  _INSERTREPLY._serialized_start=61
  _INSERTREPLY._serialized_end=90
  _QUERYREQUEST._serialized_start=92
  _QUERYREQUEST._serialized_end=119
  _QUERYREPLY._serialized_start=121
  _QUERYREPLY._serialized_end=148
  _ACTIVATEREQUEST._serialized_start=150
  _ACTIVATEREQUEST._serialized_end=167
  _ACTIVATEREPLY._serialized_start=169
  _ACTIVATEREPLY._serialized_end=200
  _REGISTERREQUEST._serialized_start=202
  _REGISTERREQUEST._serialized_end=250
  _REGISTERREPLY._serialized_start=252
  _REGISTERREPLY._serialized_end=286
  _SEARCHREQUEST._serialized_start=288
  _SEARCHREQUEST._serialized_end=332
  _SEARCHREPLY._serialized_start=334
  _SEARCHREPLY._serialized_end=364
  _PAIRINGREQUEST._serialized_start=366
  _PAIRINGREQUEST._serialized_end=399
  _PAIRINGREPLY._serialized_start=401
  _PAIRINGREPLY._serialized_end=431
  _TERMINATEREQUEST._serialized_start=433
  _TERMINATEREQUEST._serialized_end=451
  _TERMINATEREPLY._serialized_start=453
  _TERMINATEREPLY._serialized_end=484
  _PAIRSERVICE._serialized_start=487
  _PAIRSERVICE._serialized_end=704
  _CENTRALSERVICE._serialized_start=707
  _CENTRALSERVICE._serialized_end=933
# @@protoc_insertion_point(module_scope)
