# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kv.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kv.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08kv.proto\x12\x02kv\"+\n\rInsertRequest\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t\"\x1d\n\x0bInsertReply\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\x1b\n\x0cQueryRequest\x12\x0b\n\x03key\x18\x01 \x01(\x05\"\x1b\n\nQueryReply\x12\r\n\x05value\x18\x01 \x01(\t\"\x11\n\x0f\x41\x63tivateRequest\"\x1f\n\rActivateReply\x12\x0e\n\x06result\x18\x01 \x01(\x05\"0\n\x0fRegisterRequest\x12\x0f\n\x07locator\x18\x01 \x01(\t\x12\x0c\n\x04keys\x18\x02 \x03(\x05\"\"\n\rRegisterReply\x12\x11\n\tprocessed\x18\x01 \x01(\x05\",\n\rSearchRequest\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x0e\n\x06\x65xcept\x18\x02 \x01(\t\"\x1e\n\x0bSearchReply\x12\x0f\n\x07locator\x18\x01 \x01(\t\"!\n\x0ePairingRequest\x12\x0f\n\x07locator\x18\x01 \x01(\t\"\x1e\n\x0cPairingReply\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\x12\n\x10TerminateRequest\"\x1f\n\x0eTerminateReply\x12\r\n\x05total\x18\x01 \x01(\x05\x32\xd9\x01\n\x0bPairService\x12.\n\x06Insert\x12\x11.kv.InsertRequest\x1a\x0f.kv.InsertReply\"\x00\x12+\n\x05Query\x12\x10.kv.QueryRequest\x1a\x0e.kv.QueryReply\"\x00\x12\x34\n\x08\x41\x63tivate\x12\x13.kv.ActivateRequest\x1a\x11.kv.ActivateReply\"\x00\x12\x37\n\tTerminate\x12\x14.kv.TerminateRequest\x1a\x12.kv.TerminateReply\"\x00\x32\xe2\x01\n\x0e\x43\x65ntralService\x12\x34\n\x08Register\x12\x13.kv.RegisterRequest\x1a\x11.kv.RegisterReply\"\x00\x12.\n\x06Search\x12\x11.kv.SearchRequest\x1a\x0f.kv.SearchReply\"\x00\x12\x31\n\x07Pairing\x12\x12.kv.PairingRequest\x1a\x10.kv.PairingReply\"\x00\x12\x37\n\tTerminate\x12\x14.kv.TerminateRequest\x1a\x12.kv.TerminateReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kv_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INSERTREQUEST']._serialized_start=16
  _globals['_INSERTREQUEST']._serialized_end=59
  _globals['_INSERTREPLY']._serialized_start=61
  _globals['_INSERTREPLY']._serialized_end=90
  _globals['_QUERYREQUEST']._serialized_start=92
  _globals['_QUERYREQUEST']._serialized_end=119
  _globals['_QUERYREPLY']._serialized_start=121
  _globals['_QUERYREPLY']._serialized_end=148
  _globals['_ACTIVATEREQUEST']._serialized_start=150
  _globals['_ACTIVATEREQUEST']._serialized_end=167
  _globals['_ACTIVATEREPLY']._serialized_start=169
  _globals['_ACTIVATEREPLY']._serialized_end=200
  _globals['_REGISTERREQUEST']._serialized_start=202
  _globals['_REGISTERREQUEST']._serialized_end=250
  _globals['_REGISTERREPLY']._serialized_start=252
  _globals['_REGISTERREPLY']._serialized_end=286
  _globals['_SEARCHREQUEST']._serialized_start=288
  _globals['_SEARCHREQUEST']._serialized_end=332
  _globals['_SEARCHREPLY']._serialized_start=334
  _globals['_SEARCHREPLY']._serialized_end=364
  _globals['_PAIRINGREQUEST']._serialized_start=366
  _globals['_PAIRINGREQUEST']._serialized_end=399
  _globals['_PAIRINGREPLY']._serialized_start=401
  _globals['_PAIRINGREPLY']._serialized_end=431
  _globals['_TERMINATEREQUEST']._serialized_start=433
  _globals['_TERMINATEREQUEST']._serialized_end=451
  _globals['_TERMINATEREPLY']._serialized_start=453
  _globals['_TERMINATEREPLY']._serialized_end=484
  _globals['_PAIRSERVICE']._serialized_start=487
  _globals['_PAIRSERVICE']._serialized_end=704
  _globals['_CENTRALSERVICE']._serialized_start=707
  _globals['_CENTRALSERVICE']._serialized_end=933
# @@protoc_insertion_point(module_scope)
